### ISSUE TITLE
여러 성경 동시 사용 + 슬라이드당 성경 구절 줄 수 제한 시 오류 발생

### ISSUE THREAD

**Issue by sunghwan2789** [sunghwan2789/Bible2PPT#65]
## 실행 환경

* Windows 7 (32비트, 64비트)
* Office 2007, 2010
  * Office 16.0.13001.20266에서는 오류 없음

## 재현 방법

* 성경을 두 개 이상 사용한다.
* 템플릿 편집하기로 `[BODY] [BODY2]` 를 **한 줄로 입력**한다.
  * `[BODY]`와 `[BODY2]`를 각각 따로 텍스트 상자로 추가하면 오류 없음 (개발 의도)
* 슬라이드당 성경 구절 줄 수를 4줄(제한 없음 외 모두)로 설정한다.
* 성경 구절 검색어로 `레1`을 입력한다.
* PPT를 만든다.

## 오류 내용

```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Bible2PPT.PPT.JobManager.<>c__DisplayClass14_0.<<Queue>b__0>d.MoveNext() in Bible2PPT\PPT\JobManager.cs:line 49
```

**Comment by sunghwan2789** [comment]
여러 성경 본문을 각각의 텍스트 상자로 담도록 안내하기
